export default {
  HOME: '/',
  PORTUGAL: '/portugal',
  BENFICA: '/benfica',
  PORTO: '/porto',
  SPORTING: '/sporting',
  CRIANCAS: '/criancas',
  OUTROS: '/outros',
  PROMOCOES: '/promocoes',
  ACCOUNT: '/account',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDERS_REPORTS_PREBOOKING: '/admin/orders/reports/prebooking',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_NEW_PRODUCT: '/admin/new-product',
  ADMIN_PRODUCTS_CONFIG: '/admin/products-config',
  ADMIN_IMAGES: '/admin/images',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_SETTINGS_HOME_PAGE_LAYOUT: '/admin/settings/home-page-layout',
  SETTINGS: '/admin/settings',
  PRODUCT_DETAILS: '/products/:id',
  ORDER_SUMMARY: (orderId) => `/orders/${orderId}`,
  CART: '/cart',
  ORDER_RECEIVED: '/order-received',
  LOGIN: '/login',
};
