export default {
  HOME: '/',
  PORTUGAL: '/portugal',
  BENFICA: '/benfica',
  PORTO: '/porto',
  SPORTING: '/sporting',
  CRIANCAS: '/criancas',
  OUTROS: '/outros',
  ACCOUNT: '/account',
  ADMIN: '/admin',
  SETTINGS: '/admin/settings',
  PRODUCT_DETAILS: '/products/:id',
  ORDER_SUMMARY: (orderId) => `/orders/${orderId}`,
  CART: '/cart',
  ORDER_RECEIVED: '/order-received',
  LOGIN: '/login',
};
