/* eslint-disable no-underscore-dangle */
const _PENDING = '_PENDING';
const _FULFILLED = '_FULFILLED';
const _REJECTED = '_REJECTED';

export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const FETCH_SETTINGS_PENDING = FETCH_SETTINGS + _PENDING;
export const FETCH_SETTINGS_FULFILLED = FETCH_SETTINGS + _FULFILLED;
export const FETCH_SETTINGS_REJECTED = FETCH_SETTINGS + _REJECTED;

export const SAVE_SIZES = 'SAVE_SIZES';
export const SAVE_SIZES_PENDING = FETCH_SETTINGS + _PENDING;
export const SAVE_SIZES_FULFILLED = FETCH_SETTINGS + _FULFILLED;
export const SAVE_SIZES_REJECTED = FETCH_SETTINGS + _REJECTED;
